### ISSUE TITLE
Slight lag while opening GUI

### ISSUE THREAD

**Issue by RezaSmith** [TechReborn/EngineersWorkshopReborn#2]
###### **Forge Version & Engineer's Workshop Version [MAKE SURE YOU ARE RUNNING THE LATEST BUILD]**
> 14.23.0.2550
1.0.0.7

###### **Expected behavior**
> when i try to open the workshop table's GUI it has a slight delay and causing fps at the same time , its for less than a second but still a little annoying

###### **Actual Behavior**
> open up without lag

###### **Link to Crashlog or Forgelog** *[If Applicable]*
> no need i think?

###### **Steps to reproduce** *[If Applicable]*
> make a workshop table
open the GUI

**Comment by modmuss50** [comment]
I cannot reproduce this issue. I have just done a major cleanup of the code. So if you could test with the new version (should be on curse soon) to see if the issue has been fixed, that would be great. Thanks.

**Comment by RezaSmith** [comment]
well i tried to latest version and here we go , the thing is it might not be a problem but its something : 
here is a video i recorded to show you what i mean : 
https://www.youtube.com/watch?v=N2c-8gdbRSc
pay attention to the fps counter at top left

**Comment by HorizonsMC** [comment]
Getting the same issue with latest version.
